name = "frens pack 2 (real) (notclickbait)"
author = "Bob Varioa"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e27b8aa3759949137afbf0a32284d3f3e979396042a85d228e28edab46c656ce"

[versions]
minecraft = "1.20.1"
neoforge = "1.20.1-47.1.106"
