name = "frens pack 2 (real) (notclickbait)"
author = "Bob Varioa"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "77e236c2a1dbf5bf26cd4ddc5d46336cc7aa20f3bd5f7a6ae56c6f491659cbab"

[versions]
minecraft = "1.20.1"
neoforge = "1.20.1-47.1.106"
