name = "frens pack 2 (real) (notclickbait)"
author = "Bob Varioa"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f6af7d563ac2d5383da5acb2cdf262f9e07e10de6f3fc5140fe9960c9817350e"

[versions]
minecraft = "1.20.1"
neoforge = "1.20.1-47.1.106"
