name = "frens pack 2 (real) (notclickbait)"
author = "Bob Varioa"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "094fe61d42206d299b090eb6ea672763f42ff7ba7be687f9946218318a97f6c7"

[versions]
minecraft = "1.20.1"
neoforge = "1.20.1-47.1.106"
