name = "frens pack 2 (real) (notclickbait)"
author = "Bob Varioa"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "29b1b29401e97c0b19c5fad034a0e1b3ea4246126785fc4c5814077d15f6d39f"

[versions]
minecraft = "1.20.1"
neoforge = "1.20.1-47.1.106"
