name = "frens pack 2 (real) (notclickbait)"
author = "Bob Varioa"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "494082038aafbfe86df4d232391af2ba5d267124b9766419fe038f654544dcc5"

[versions]
minecraft = "1.20.1"
neoforge = "1.20.1-47.1.106"
