name = "frens pack 2 (real) (notclickbait)"
author = "Bob Varioa"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9b6c1d9cf38c7074e9c28c37c95ce313c39127413b3238c4dac61cce74bd02d2"

[versions]
minecraft = "1.20.1"
neoforge = "1.20.1-47.1.106"
