name = "frens pack 2 (real) (notclickbait)"
author = "Bob Varioa"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4d417efa0dfacc84505967f5209e971bb02f9ca5c0f70844a315bce34b9c8314"

[versions]
minecraft = "1.20.1"
neoforge = "1.20.1-47.1.106"
